### ISSUE TITLE
Missing PHP Extensions

### ISSUE THREAD

**Issue by tatwell** [robertdebock/ansible-role-mediawiki#1]
Thanks for putting together this Ansible playbook.

I've run the playbook as outlined in the README (I did need to add the PHP explicitly to my playbook). Once complete, when I visit the wiki in my browser, I get this message:

---

### MediaWiki 1.31 internal error
Installing some PHP extensions is required.

#### Required components
You are missing a required extension to PHP that MediaWiki requires to run. Please install:

- mbstring (more information)
- xml (more information)

---

I've looked both at this role and the PHP role and I can't figure out quite where I would configure the playbook to install these. Any suggestions? 

I'm running it on Ubuntu 18.1.

Let me know if I can provide any additional info. Thanks.

**Comment by robertdebock** [comment]
I'll look at it, hope I have enough information. Speak to you later.

**Comment by tatwell** [comment]
Thanks, Robert.

Here's my `playbook.yml` file for reference:

```
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mediawiki
```

I know when I set up Mediawiki manually not too long ago I had to install these extensions. I could probably add my own role pretty easily to handle this. But it seems like the sort of task that would fall within the scope of one of the existing roles, so I'd prefer to do it there if possible.
