### ISSUE TITLE
How to set up an SSL version of the site?

### ISSUE THREAD

**Issue by tatwell** [robertdebock/ansible-role-mediawiki#3]
I'm trying to set this up to run on VirtualBox on localhost. I got the non-SSL version running ok.

I've done this on a local VirtualBox before using this role to create my own certificate (the browser complains but I'm ok with that):

- https://github.com/openmicroscopy/ansible-role-ssl-certificate

This is my config file:

```
#
# Role: robertdebock.httpd
# https://github.com/robertdebock/ansible-role-httpd
#
httpd_ssl_servername: "localhost"
httpd_port: 8000
httpd_ssl_port: 8443

httpd_vhosts:
  - name: mediawiki
    servername: localhost
    documentroot: /var/www/html/mediawiki
```

With this config, I get the **This site can’t be reached** message from my browser.

I was wondering if you could recommend an approach using your roles.

Thanks!

**Comment by robertdebock** [comment]
Thanks @tatwell, I'll reproduce this and hand back a playbook that [works on my machine](https://www.teepublic.com/t-shirt/2305863-programmer-t-shirt-it-works-on-my-machine).

**Comment by robertdebock** [comment]
I've got [this test repository](https://github.com/robertdebock/ansible-tester/blob/master/mediawiki.yml) that seems to work.

I've used/done:
- Fedora
- https://ip.ip.ip.ip/mediawiki

I do notice a missing package (`php-json`) in the mediawiki role. Testing it now, releasing it later.

Let me know if this helps you, closing the issue now, but feel free to reopen it.

**Comment by tatwell** [comment]
Still not having any luck. It may just be a VirtualBox config issue on my end. I'll have to look more closely how I've managed this in the past.

I'm curious how the SSL certificate gets set up in your example.

**Comment by robertdebock** [comment]
Hm, strange, can you give me the code of the stuff that's not working? Are you setting up the virtualbox using vagrant? What is the output of the playbook?

SSL is setup in the httpd role.

**Comment by tatwell** [comment]
I set up VirtualBox from the command line. I don't have experience with Vagrant.

I think this is the relevant code:

#### playbook.yml

```
#
# To run playbook:
#   cd devops/ansible
#   ansible-playbook playbook.yml -i hosts/virtualbox
#
# To run specific roles, tag the role(s) dev and use the --tags option:
#   ansible-playbook playbook.yml -i hosts/virtualbox --tags dev -v
#
# See group_vars/playbook for more info on each role.
#
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mysql
    - robertdebock.mediawiki
```

#### host_vars/virtualbox

```
#
# Role: robertdebock.mysql
# https://github.com/robertdebock/ansible-role-mysql
#
mysql_bind_address: 127.0.0.1

# This role can populate databases and users, see below.
mysql_databases:
  - name: mediawiki

mysql_users:
  - name: mediawiki
    password: mediawiki
    priv: "mediawiki.*:ALL"
    host: localhost

#
# Role: robertdebock.httpd
# https://github.com/robertdebock/ansible-role-httpd
#
httpd_ssl_servername: "localhost"
httpd_port: 8000
httpd_ssl_port: 8443

httpd_vhosts:
  - name: mediawiki
    servername: localhost
    documentroot: /var/www/html/mediawiki
```

The playbook runs successfully:

```
$ ansible-playbook playbook.yml -i hosts/virtualbox --ask-become-pass

PLAY RECAP ***********************************************************************
virtualbox                 : ok=45   changed=27   unreachable=0    failed=0
```

Only other unusual output:

```
TASK [robertdebock.bootstrap : test connection] *********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'e' referenced before assignment              
fatal: [virtualbox]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}                                                                             
...ignoring                                                                                                                                                                      
```

I can access at http://localhost:8000/mediawiki or http://127.0.0.1:8000/mediawiki.

Get error above at https://localhost:8443/mediawiki or https://127.0.0.1:8443/mediawiki.
